### PR TITLE
fix(device-mutex): use global crypto.randomUUID instead of importing from crypto module

### PR DESCRIPTION
**Pull request by PeKne**
## Description

- `requestDeviceAccess.ts` imported `randomUUID` from the `'crypto'` Node module, which Metro resolves to `crypto-browserify` — a polyfill that does not expose `randomUUID`
- Switched to `crypto.randomUUID()` (bare global), which is correctly provided by `react-native-quick-crypto` patching `global.crypto` in `globalPolyfills.js`
- Regression introduced in #28502 (`a0f5a88509`)

## Notes for QA

- Navigate to a receive address screen with a hardware wallet connected
- Tap "Show address" and confirm on the device — should complete without throwing `TypeError: crypto.randomUUID is not a function`

## 🔍 Currents Test Results

🔍 **Suite native android test results:** [View in Currents](https://app.currents.dev/projects/iUe1Y4/runs?branch=fix/device-mutex-crypto-random-uuid&lookback=7)

🔍 **Suite web test results:** [View in Currents](https://app.currents.dev/projects/Og0NOQ/runs?branch=fix/device-mutex-crypto-random-uuid&lookback=7)

<details>
<summary><h3>🤖 LLM Test Recommendations</h3></summary>

**Summary:** All three changed files are in the suite-native ecosystem (jest.config.native.js, suite-native/device-mutex/src/requestDeviceAccess.ts, suite-native/test-utils/src/mocks/randomUUIDMock.js). These are native mobile-specific files: a Jest config for native tests, a device mutex utility for native device access, and a UUID mock for native test utilities. None of the 136 candidate E2E tests cover suite-native functionality — they all target the suite-web or suite-desktop (Electron) platforms. There is no static mapping and no inferred connection between these native-only changes and any of the Playwright E2E tests. The risk to the web/desktop E2E test suite is effectively zero; unit tests within the suite-native package would be the appropriate coverage mechanism.

<details><summary><b>Changed files (3)</b></summary>

- `jest.config.native.js`
- `suite-native/device-mutex/src/requestDeviceAccess.ts`
- `suite-native/test-utils/src/mocks/randomUUIDMock.js`

</details>

_No test recommendations found._

⚠️ **Changes with no test coverage (3)**
- `jest.config.native.js`
- `suite-native/device-mutex/src/requestDeviceAccess.ts`
- `suite-native/test-utils/src/mocks/randomUUIDMock.js`

_Updated: 2026-06-16T07:34:52.435Z_

</details>

## 🌐 Preview deployments

🌐 **Suite Web preview:** [https://dev.suite.sldev.cz/suite-web/fix/device-mutex-crypto-random-uuid/web/](https://dev.suite.sldev.cz/suite-web/fix/device-mutex-crypto-random-uuid/web/)

## 🔒 Quarantined E2E Tests

<details><summary>Trezor Suite (desktop) — 3 test(s)</summary>

| Test | Type |
|------|------|
| Send Base > User can perform ethereum sending on base network | 🤖 auto |
| Labeling migration > Migration from local file | 🤖 auto |
| Quarantine test: "Multiple sessions,Session overtaken by another" | 🙋 manual |

</details>

_Updated: 2026-06-16T07:38:25.199Z • 3 test(s) total_

<details><summary>Trezor Suite (web) — 6 test(s)</summary>

| Test | Type |
|------|------|
| Account metadata > dropbox provider | 🤖 auto |
| Remembered wallet loading > Load remembered wallet and open receive forms without connected device | 🤖 auto |
| Quarantine test: "Onboarding - create wallet,Success (basic)" | 🙋 manual |
| Quarantine test: "Database migration,Db migration between: release/22.5/web => develop/web" | 🙋 manual |
| Quarantine test: "Multiple sessions,Session overtaken by another" | 🙋 manual |
| Quarantine test: "Recovery T2T1 - dry run,Recovery after partial recovery" | 🙋 manual |

</details>

_Updated: 2026-06-16T07:38:21.645Z • 6 test(s) total_

### CODE REVIEW

**Review by yanascz — APPROVED** [review]
LGTM

**Comment by honzauher** [comment]
QA OK based on notes

No errors

Info:
- iOS
- develop-26.7.1, commit db13446f
